# version: 2.1

# jobs:
#   aqua-trivy:
#     machine:
#       image: ubuntu-2004:202010-01
#     steps:
#       - checkout
#       - run: |
#           printenv
#           export trivyVersion=0.32.0
#           export TRIVY_RUN_AS_PLUGIN=aqua
#           curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b . v${trivyVersion}
#           ./trivy plugin install github.com/tzurielweisberg/plugin-version
#           ./trivy fs --security-checks config,vuln,secret .
          
# workflows:
#   aqua-trivy-workflow:
#     jobs:
#       - aqua-trivy
