name: Create/update tag
on:
  workflow_dispatch:
jobs:
  create-tagas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: | 
          git push --delete origin latest
      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "latest"
          tag_exists_error: false
          message: "Latest release"

      # Print result using the env variable.
      -  run: |
          echo "Tag already present: ${{ env.TAG_EXISTS }}"

      # Print result using the action output.
      - run: |
          echo "Tag already present: ${{ steps.tag_create.outputs.tag_exists }}"
