name: create pr

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update plugin Links
        run: |
          echo ${{github.ref_name}}
